### ISSUE TITLE
VPN - Wireguard can't connect to server

### ISSUE THREAD

**Issue by keks1337** [DeadSquirrel01/lineage-16_a5_releases#28]
Hi
since i update to your ROM i cant connect to my wireguard server.

Logs from Wireguard:
`
--------- beginning of main
05-03 15:13:16.872 21803 21803 D OpenGLRenderer: Skia GL Pipeline
--------- beginning of events
05-03 15:13:16.961 21803 21803 I am_on_create_called: [0,com.wireguard.android.activity.MainActivity,performCreate]
05-03 15:13:16.971 21803 21803 I am_on_start_called: [0,com.wireguard.android.activity.MainActivity,handleStartActivity]
05-03 15:13:16.974 21803 21803 I am_on_resume_called: [0,com.wireguard.android.activity.MainActivity,RESUME_ACTIVITY]
05-03 15:13:17.056 21803 21831 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.6_RB1__release_AU (Ia10634f51b)
05-03 15:13:17.056 21803 21831 I Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.06.00.05
05-03 15:13:17.056 21803 21831 I Adreno-EGL: Build Date: 01/04/16 Mon
05-03 15:13:17.056 21803 21831 I Adreno-EGL: Local Branch: 
05-03 15:13:17.056 21803 21831 I Adreno-EGL: Remote Branch: quic/LA.BR.1.2.6_rb1.7
05-03 15:13:17.056 21803 21831 I Adreno-EGL: Local Patches: NONE
05-03 15:13:17.056 21803 21831 I Adreno-EGL: Reconstruct Branch: NOTHING
05-03 15:13:17.064 21803 21831 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
05-03 15:13:17.064 21803 21831 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
05-03 15:13:17.064 21803 21831 I OpenGLRenderer: Initialized EGL, version 1.4
05-03 15:13:17.065 21803 21831 D OpenGLRenderer: Swap behavior 1
05-03 15:13:17.071 21803 21831 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
05-03 15:13:17.092 21803 21831 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
05-03 15:13:17.097 21803 21831 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8916.so from current namespace instead of sphal namespace.
05-03 15:13:17.217 21803 21831 D vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
05-03 15:13:17.218 21803 21831 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8916.so from current namespace instead of sphal namespace.
05-03 15:13:18.479 21803 21803 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
05-03 15:13:18.480 21803 21803 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
05-03 15:13:19.768 21803 21821 D WireGuard/GoBackend: Changing tunnel work1 to state UP
05-03 15:13:19.768 21803 21821 I WireGuard/GoBackend: Bringing tunnel up
05-03 15:13:19.770 21803 21821 D WireGuard/GoBackend: Requesting to start VpnService
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: Error bringing up tunnel: Remote stack trace:
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.android.server.connectivity.Vpn.establish(Vpn.java:1056)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.android.server.ConnectivityService.establishVpn(ConnectivityService.java:3705)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:577)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Binder.execTransact(Binder.java:731)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: java9.util.concurrent.CompletionException: java.lang.IllegalArgumentException: At least one address must be specified
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java9.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:357)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java9.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:367)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java9.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1084)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java9.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:504)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java9.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2151)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.util.AsyncWorker.lambda$null$4(AsyncWorker.java:48)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.util.-$$Lambda$AsyncWorker$0jVCYNboBOWw9K-jArH8OB3SmXI.run(Unknown Source:4)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Handler.handleCallback(Handler.java:873)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Looper.loop(Looper.java:193)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java.lang.reflect.Method.invoke(Native Method)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: Caused by: java.lang.IllegalArgumentException: At least one address must be specified
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Parcel.createException(Parcel.java:1954)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Parcel.readException(Parcel.java:1918)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Parcel.readException(Parcel.java:1868)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1984)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.net.VpnService$Builder.establish(VpnService.java:806)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.backend.GoBackend.setStateInternal(GoBackend.java:174)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.backend.GoBackend.setState(GoBackend.java:116)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.model.TunnelManager.lambda$null$18(TunnelManager.java:250)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.model.-$$Lambda$TunnelManager$fAapFPNRxx6EfgD7SEnbhcfuzuM.get(Unknown Source:4)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.util.AsyncWorker.lambda$supplyAsync$5(AsyncWorker.java:45)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.wireguard.android.util.-$$Lambda$AsyncWorker$wP6ZO_lwMWxn1CVpUfnLV0bfA18.run(Unknown Source:6)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at java.lang.Thread.run(Thread.java:764)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: Caused by: android.os.RemoteException: Remote stack trace:
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.android.server.connectivity.Vpn.establish(Vpn.java:1056)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at com.android.server.ConnectivityService.establishVpn(ConnectivityService.java:3705)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.net.IConnectivityManager$Stub.onTransact(IConnectivityManager.java:577)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: 	at android.os.Binder.execTransact(Binder.java:731)
05-03 15:13:19.869 21803 21803 E WireGuard/BaseFragment: `

I know its not your app but i think the app is not the problem. The app works fine before i update.

btw 
great job!

**Comment by DeadSquirrel01** [comment]
try other vpn apps, if that's the only one which doesn't work, it means that it doesnt work with our rom/custom roms
