### ISSUE TITLE
Crash when trying to enable Dark Style

### ISSUE THREAD

**Issue by d0rkye** [DeadSquirrel01/lineage-16_a5_releases#5]
When i'm tying to set Settings --> Display --> Style --> Dark mode --> Black
the settings app crashes here is the logcat section for it if it helps.

Thank you for your great work.

`FATAL EXCEPTION: main
Process: org.lineageos.lineageparts, PID: 2742
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.om.OverlayInfo.isEnabled()' on a null object reference
at android.os.Parcel.createException(Parcel.java:1948)
at android.os.Parcel.readException(Parcel.java:1910)
at android.os.Parcel.readException(Parcel.java:1860)
at lineageos.style.IStyleInterface$Stub$Proxy.setDarkOverlay(IStyleInterface.java:307)
at lineageos.style.StyleInterface.setDarkOverlay(StyleInterface.java:326)
at org.lineageos.lineageparts.style.StylePreferences.onDarkChange(StylePreferences.java:156)
at org.lineageos.lineageparts.style.StylePreferences.lambda$Jp18abi33tiGGLxaIJse2UrBfqY(Unknown Source:0)
at org.lineageos.lineageparts.style.-$$Lambda$StylePreferences$Jp18abi33tiGGLxaIJse2UrBfqY.onPreferenceChange(Unknown Source:2)
at android.support.v7.preference.Preference.callChangeListener(Preference.java:1060)
at android.support.v14.preference.ListPreferenceDialogFragment.onDialogClosed(ListPreferenceDialogFragment.java:110)
at android.support.v14.preference.PreferenceDialogFragment.onDismiss(PreferenceDialogFragment.java:270)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1393)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.RemoteException: Remote stack trace:
at org.lineageos.platform.internal.StyleInterfaceService.isEnabled(StyleInterfaceService.java:261)
at org.lineageos.platform.internal.StyleInterfaceService.setDarkOverlayInternal(StyleInterfaceService.java:201)
at org.lineageos.platform.internal.StyleInterfaceService.access$800(StyleInterfaceService.java:48)
at org.lineageos.platform.internal.StyleInterfaceService$1.setDarkOverlay(StyleInterfaceService.java:393)
at lineageos.style.IStyleInterface$Stub.onTransact(IStyleInterface.java:129)`

**Comment by krmax44** [comment]
Having the same issue, but Lineage itself is probably to blame here.

**Comment by DeadSquirrel01** [comment]
Yes, the problem is in lineage, not in the port

**Comment by d0rkye** [comment]
Ok thank you , I just thought I report this.
